// Generated by typings
// Source: https://raw.githubusercontent.com/dsherret/server-bridge/750a3f62a717e2c4a10836167cc8fcc5e3bbf360/server-bridge.d.ts
declare module '~server-bridge/server-bridge' {
interface Options {
    classMapping?: { [className: string]: string };
    importMapping?: { [importName: string]: string };
    libraryName?: string;
    includeDocumentation?: boolean;
    files: string[];
}
interface RouteDefinition {
    method: Method;
    name: string;
    func: Function;
}

export class Routes {
    routeDefinitions: RouteDefinition[];
    basePath: string;
}

export function getGeneratedCode(options: Options): string;
export function Get(route?: string): (target: Routes, methodName: string, descriptor: TypedPropertyDescriptor<(obj: any) => Promise<any>>) => void;
export function Post(route?: string): (target: Routes, methodName: string, descriptor: TypedPropertyDescriptor<(sentObject: any) => Promise<any>>) => void;
export function Use(basePath?: string): (target: typeof Routes) => void;

const enum Method {
    Get = 0,
    Post = 1
}
}
declare module 'server-bridge/server-bridge' {
export * from '~server-bridge/server-bridge';
}
declare module 'server-bridge' {
export * from '~server-bridge/server-bridge';
}
